# PyTorch Fundamentals

**What is PyTorch?**

PyTorch is an opensource machine learning and deep learning framework.

**What can PyTorch be used for?**

PyTorch allows us to manipulate and process data and write machine learning algorithms using Python code.

**Who uses PyTorch?**

Many of the worlds largest technology companies such as **Meta**, **Tesla** and **Microsoft** as well as artificial intelligence research companies such as **OpenAI** use PyTorch to power research and bring machine learning to their products.

## Introduction to Tensors

### Creating Tensors

PyTorch tensors are created using `torch.Tensor()`

In [1]:
# Import pytorch & check its version
import torch
print(torch.__version__)

1.12.1+cu113


In [2]:
# Create a scalar (zero dimensional tensor)
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Check the number of dimensions of a scalar
scalar.ndim

0

In [4]:
# Get tensor back as Python int
scalar.item()

7

In [5]:
# Create a vector (one dimensional tensor)
vector = torch.tensor([6, 8, 10])
vector 

tensor([ 6,  8, 10])

In [6]:
# Check the number of dimensions of a vector
vector.ndim

1

In [7]:
# Get the shape of the vector
vector.shape

torch.Size([3])

In [8]:
# Create a matrix (two dimensional tensor)
matrix = torch.tensor([[6, 8],
                      [5, 12]])
matrix

tensor([[ 6,  8],
        [ 5, 12]])

In [9]:
# Check the number of dimensions of a matrix
matrix.ndim

2

In [10]:
# Get the zeroth axis of the matrix
matrix[0]

tensor([6, 8])

In [11]:
# Get the shape of the matrix
matrix.shape

torch.Size([2, 2])

In [12]:
# Create a tensor
tensor = torch.tensor([[[3, 4, 5],
                        [5, 12, 13],
                        [8, 15, 17]]])
tensor

tensor([[[ 3,  4,  5],
         [ 5, 12, 13],
         [ 8, 15, 17]]])

In [13]:
# Get the shape & the number of dimensions of the matrix
tensor.shape, tensor.ndim

(torch.Size([1, 3, 3]), 3)

### Random Tensors

Random tensors are important because the way many neural networks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

In [14]:
# Create a random tensor of size (1, 3, 4)
random_tensor = torch.rand(1, 3, 4)
random_tensor

tensor([[[0.8819, 0.1758, 0.3766, 0.4384],
         [0.8790, 0.3566, 0.6845, 0.3541],
         [0.6304, 0.7253, 0.9719, 0.1226]]])

In [15]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size = (3, 224, 224)) # colour channels, height, width
random_image_size_tensor

tensor([[[0.7718, 0.7990, 0.4782,  ..., 0.9725, 0.9020, 0.8012],
         [0.7036, 0.2524, 0.8076,  ..., 0.1472, 0.1113, 0.2929],
         [0.7197, 0.7934, 0.3152,  ..., 0.8436, 0.5810, 0.3949],
         ...,
         [0.3527, 0.2314, 0.0791,  ..., 0.6126, 0.1585, 0.8987],
         [0.3697, 0.0310, 0.1635,  ..., 0.9296, 0.7728, 0.1730],
         [0.1112, 0.1722, 0.5185,  ..., 0.2730, 0.8317, 0.6337]],

        [[0.4173, 0.9797, 0.5665,  ..., 0.2137, 0.9613, 0.9601],
         [0.1011, 0.1880, 0.3108,  ..., 0.2842, 0.2750, 0.5505],
         [0.6097, 0.5102, 0.8789,  ..., 0.6948, 0.7835, 0.7202],
         ...,
         [0.4150, 0.3035, 0.4547,  ..., 0.9752, 0.9290, 0.2940],
         [0.0495, 0.4822, 0.1162,  ..., 0.9953, 0.5191, 0.5597],
         [0.6970, 0.8987, 0.9517,  ..., 0.0826, 0.2681, 0.4831]],

        [[0.4158, 0.8251, 0.6780,  ..., 0.2808, 0.2695, 0.1117],
         [0.2918, 0.7056, 0.9289,  ..., 0.8394, 0.4077, 0.6526],
         [0.5634, 0.5431, 0.3218,  ..., 0.8794, 0.2062, 0.

In [16]:
# Check the shape & the number of dimensions of the random tensor
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

### Zeros & ones

In [17]:
# Create a tensor of all zeros
zeros = torch.zeros(size = (1, 3, 4))
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [18]:
# Create a tensor of all ones
ones = torch.ones(size = (1, 3, 4))
ones

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [19]:
# Check the datatype of both
zeros.dtype, ones.dtype

(torch.float32, torch.float32)

### Creating a range of tensors & tensors-like

In [20]:
# Use torch.range()
torch.range(0, 10)

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [21]:
# Use torch.arange()
one_to_ten = torch.arange(start = 0, end = 11, step = 1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
# Creating tensors like
ten_zeroes = torch.zeros_like(input = one_to_ten)
ten_zeroes

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors we'll run into with PyTorch & Deep Learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device



In [23]:
# Create Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None, # what datatype is the tensor (e.g float32 or float16)
                               device = None, # what device is your tensor on
                               requires_grad = False) # whether or not to track gradients with this tensors operations

In [24]:
# Create Float 16 tensor
float_16_tensor = float_32_tensor.type(torch.float16)

### Getting informations from tensors (tensor attributes)

1. To get datatype from a tensor, we can use `tensor.dtype`
2. To get shape from a tensor, we may use `tensor.shape`
3. To get device from a tensor, we can use `tensor.device`

In [25]:
# Create tensor 
some_tensor = torch.rand(3, 4)
some_tensor

tensor([[0.8444, 0.7475, 0.8637, 0.3665],
        [0.7386, 0.3532, 0.3929, 0.6682],
        [0.8908, 0.2304, 0.5684, 0.2166]])

In [26]:
# Find out details about some tensor
print(some_tensor)
print(f'\nDatatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}')
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.8444, 0.7475, 0.8637, 0.3665],
        [0.7386, 0.3532, 0.3929, 0.6682],
        [0.8908, 0.2304, 0.5684, 0.2166]])

Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Divison
* Matrix Multiplication


In [27]:
# Create a tensor & add 10 to it
tensor = torch.tensor([1, 2 ,3])
tensor + 10

tensor([11, 12, 13])

In [28]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [29]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [30]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [31]:
torch.add(tensor, 10)

tensor([11, 12, 13])

### Matrix Multiplication

Two main ways of performing multiplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix multiplication (dot product)

There are two main rules that performing matrix multiplication needs to satisfy:
1. The **inner dimensions** must match:
* `(3, 2) @ (2, 3)` will work but, `(2, 3) @ (2, 3)` won't work 
2. The resulting matrix has the shape of the **outer dimensions**:
* `(2, 3) @ (3, 2)` -> `(2, 2)`

In [32]:
# Element wise multiplication 
tensor * tensor

tensor([1, 4, 9])

In [33]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

### One of the most common errors in deep learning: shape errors

In [34]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

# torch.mm(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for writing less code)
torch.matmul(tensor_A, tensor_B)

RuntimeError: ignored

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose**.

A **transpose** switches the axes of a given tensor.

In [35]:
# Original tensor_B
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]), torch.Size([3, 2]))

In [36]:
# Transposed tensor_B
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]), torch.Size([2, 3]))

In [37]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}")
print(f"New shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.T.shape}")
print(f"Multiplying: {tensor_A.shape} @ {tensor_B.shape} <- inner dimensions must match")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"Output shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([3, 2]) <- inner dimensions must match
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])
Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum, etc (tensor aggregation)

In [38]:
# Create a tensor 
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [39]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [40]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [41]:
# Find the mean
torch.mean(x)

RuntimeError: ignored

In [42]:
# Check the datatype of x
x.dtype

torch.int64

In [43]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

🔑 **Note:** The `torch.mean()` function requires a tensor of float32 datatype to work 

In [44]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [45]:
# Find the position in tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs
torch.argmin(x)

tensor(0)

In [46]:
# Find the position in tensor that has the maximum value with argmin()
torch.argmax(x)

tensor(9)

## Reshaping, stacking, squeezing and unsqueezing tensors

* **Reshaping** - reshapes an input tensor to a defined shape
* **View** - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* **Stacking** - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* **Squeeze** - removes all `1` dimensions from a tensor
* **Unsqueeze** - add a `1` dimension to a target tensor
* **Permute** - Return a view of the input with dimensions permuted (swapped) in a certain way

In [47]:
# Let's create a tensor 
x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [48]:
# Add an extra dimension 
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]), torch.Size([9, 1]))

In [49]:
# Create another tensor 
x2 = torch.arange(1, 12)
x2, x2.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]), torch.Size([11]))

In [50]:
# Add an extra dimension to x2
x2_reshaped = x2.reshape(11, 1)
x2_reshaped, x2_reshaped.shape

(tensor([[ 1],
         [ 2],
         [ 3],
         [ 4],
         [ 5],
         [ 6],
         [ 7],
         [ 8],
         [ 9],
         [10],
         [11]]), torch.Size([11, 1]))

In [51]:
# Change the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [52]:
# Changing z changes x (because a view of a tensor shares the same memory as the original input)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [53]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x, x], dim = 0) # dim = 0 -> vertical, dim = 1 -> horizontal
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [54]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimensions from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])
Previous shape: torch.Size([9, 1])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


In [55]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dimension
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim = 0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [56]:
# torch.permute() - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size = (224, 224, 3)) # height, width, colour_channels

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") 

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy

In [57]:
# Create a tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]), torch.Size([1, 3, 3]))

In [58]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [59]:
# Let's index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [60]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0]

tensor(1)

In [61]:
# We may also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [62]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [63]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [64]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [65]:
# Numpy array to tensor
import torch
import numpy as np 

# Create an array
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) 
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [66]:
# Check the default datatypes of numpay array & tensors
array.dtype, torch.arange(1.0, 80).dtype

(dtype('float64'), torch.float32)

🔑 **Note:** When converting from numpy -> pytorch, pytorch reflects numpy's default datatype of float64 unless specified otherwise.

In [67]:
# Change the value of array, what will this do to tensor? (doesn't affect it!)
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [68]:
# Tensor to NumPy array 
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [69]:
# Change the tensor, what happens to numpy_tensor? (does not affect as well!)
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short, how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed** 

Essentially what the random seed does is "flavour" the randomness.

In [70]:
# Create a tensor
torch.rand(3, 3)

tensor([[0.2673, 0.9744, 0.1251],
        [0.6593, 0.6628, 0.2129],
        [0.9018, 0.5654, 0.0640]])

In [71]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.8814, 0.5729, 0.6662, 0.4342],
        [0.6994, 0.3863, 0.3842, 0.9081],
        [0.8780, 0.8541, 0.8618, 0.2236]])
tensor([[0.2877, 0.7610, 0.1160, 0.1442],
        [0.3927, 0.5830, 0.1665, 0.8199],
        [0.4597, 0.9821, 0.6314, 0.6501]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [72]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed 
RANDOM_SEED  =42
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA hardware + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU 

1. **Easiest** - Use Google Colab for a free GPU (options to upgrade as well)
2. **Use your own GPU** - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options
3. **Use cloud computing** - GCP, AWS, Azure, these services allow us to rent computers on the cloud and access them

In [73]:
!nvidia-smi

Mon Nov 21 10:56:48 2022       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 460.32.03    Driver Version: 460.32.03    CUDA Version: 11.2     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   52C    P8    10W /  70W |      0MiB / 15109MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

### 2. Check for GPU access with PyTorch

In [74]:
# Check for GPU access with PyTorch
import torch 
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code

E.g. run on GPU if available, else default to CPU

In [75]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [76]:
# Count number of devices 
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [77]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3]) # device is CPU as default

# Tensor not on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [78]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [79]:
# If tensor is on GPU, can't transform it to NumPy
tensor_on_gpu.numpy()

TypeError: ignored

In [80]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])